Commit without update methods, connection pool, exceptions
iryna-pantsialeyeva/final_project pull request #1
Opened 2022-09-11 17:21 UTC by iryna-pantsialeyeva

Please review my project (version 1)

2022-09-12 13:26 UTC, DimaLamaka requested changes
я не знаю для чего тут фабрики и какую проблему они решают, но мне понравилось, как ты сделала это задание) чуть поправь и вообще крутяк будет :)

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/dao/impl/SQLAuthorDAO.java
> +    }
используй try с ресурсами и не забывай закрывать стейтмент

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/dao/impl/SQLAuthorDAO.java
> +            PreparedStatement ps = con.prepareStatement(sql);
вприцнипе тут переменная sql лишняя, в стеймент можешь сразу передавать SQLRequest.ADD_AUTHOR_BY_NAME

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/dao/impl/SQLAuthorDAO.java
> +        return false;
тоже самое

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/dao/impl/SQLAuthorDAO.java
> +        return idAuthor;
тоже самое

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/dao/impl/SQLBookDAO.java
> +    public void addBook(String name, String isbn, String author, String genre) {
лучше тут принимать объект книги, а сборку книги делать в сервисном слое

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/dao/impl/SQLBookDAO.java
> +    private DataSourceUtil connectionManager = DataSourceUtil.getInstance();
лучше инициализируй переменные в конструкторе

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/dao/impl/SQLBookDAO.java
> +    }
тоже самое про try с ресурсами и стейтмент

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/dao/impl/SQLBookDAO.java
> +        }
тоже самое про try с ресурсами и стейтмент

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/dao/impl/SQLBookDAO.java
> +                book.setId((long) rs.getInt(1));
зачем кастить ? как я помню у ResultSet есть метод getLong()

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/dao/impl/SQLAuthorDAO.java
> +            String sql = SQLRequest.RETURN_AUTHOR_ID + "\'" + author + "\'";
посмотри про String.format через него удобно запросы писать

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/dao/impl/SQLBookDAO.java
> +                }
тоже самое про try с ресурсами и стейтмент

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/dao/impl/SQLBookDAO.java
> +            e.printStackTrace();
вообще уже не закрываешь, ни connection, ни стейтмент

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/dao/impl/SQLGenreDAO.java
> +            }
тоже самое про try с ресурсами и стейтмент

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/dao/impl/SQLGenreDAO.java
> +            }
лучше добавь возвращемый тип, хотя бы кол-во обновленыхх строк, а то не понятно, добавился жанр или нет

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/dao/impl/SQLGenreDAO.java
> +                e.printStackTrace();
лучше добавь возвращемый тип, хотя бы кол-во обновленыхх строк, а то не понятно, добавился жанр или нет

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/dao/impl/SQLGenreDAO.java
> +                    con.close();
тоже самое про try с ресурсами и стейтмент

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/dao/util/DataSourceUtil.java
> +        this.password = StaticVariable.PASSWORD;
поля инициализурй в этом классе, StaticVariable лишний класс

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/view/MainMenu.java
> +                    System.exit(0);
сделай просто return

2022-09-12 13:26 UTC, DimaLamaka commented on src/finalproject/part1/view/MainMenu.java
> +        Scanner scStr = new Scanner(System.in);
для чего два сканера? закрывать тоже не забывай)

2022-09-12 13:53 UTC, RomanKashenok reviewed
Замечания не критичные - можешь попроавить и мержить. Дима чуть глубже посмотрел, так что, раз уж накомментили - придется поправить )))

2022-09-12 13:53 UTC, RomanKashenok commented on src/finalproject/part1/bean/Book.java
> +    private Author a;
давай осмысленно переименуем поля (author, genre и т.п.)

2022-09-12 13:53 UTC, RomanKashenok commented on src/finalproject/part1/dao/util/DataSourceUtil.java
> +            Class.forName(driverPath);
не оч хорошо это - каждый раз пытаться загрузать драйвер (скорее всего ты используешь последний и он там внутри в статик блоке сам подгружается). Лучше коннекшн вообще не закрывать, пока пользуемся приложением (ты закрываешь каждый раз)

2022-09-12 13:53 UTC, RomanKashenok commented on src/finalproject/part1/dao/impl/SQLBookDAO.java
> +                con.close();
положи свой коннекшн везде в ресурсы блока try

2022-09-12 13:53 UTC, RomanKashenok commented on src/finalproject/part1/service/ServiceFactory.java
> +    public static ServiceFactory getInstance() {
Не вижу смысла в методе. Проще сделать переменную паблик - смысл тот же

2022-09-15 20:48 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/impl/SQLAuthorDAO.java
> +    }
Done

2022-09-15 20:48 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/impl/SQLAuthorDAO.java
> +            PreparedStatement ps = con.prepareStatement(sql);
Done

2022-09-15 20:49 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/impl/SQLAuthorDAO.java
> +        return false;
Done

2022-09-15 20:49 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/impl/SQLAuthorDAO.java
> +        return idAuthor;
Done

2022-09-15 20:49 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/impl/SQLBookDAO.java
> +    public void addBook(String name, String isbn, String author, String genre) {
Done

2022-09-15 20:50 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/impl/SQLBookDAO.java
> +    private DataSourceUtil connectionManager = DataSourceUtil.getInstance();
Done

2022-09-15 20:50 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/impl/SQLBookDAO.java
> +    }
Done

2022-09-15 20:50 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/impl/SQLBookDAO.java
> +        }
Done

2022-09-15 20:50 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/impl/SQLBookDAO.java
> +                book.setId((long) rs.getInt(1));
Done

2022-09-15 20:50 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/impl/SQLAuthorDAO.java
> +            String sql = SQLRequest.RETURN_AUTHOR_ID + "\'" + author + "\'";
Done

2022-09-15 20:50 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/impl/SQLBookDAO.java
> +                }
Done

2022-09-15 20:50 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/impl/SQLBookDAO.java
> +            e.printStackTrace();
Done

2022-09-15 20:52 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/impl/SQLGenreDAO.java
> +            }
Fixed with sout.

2022-09-15 20:52 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/impl/SQLGenreDAO.java
> +                e.printStackTrace();
Fixed with sout.

2022-09-15 20:52 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/impl/SQLGenreDAO.java
> +                    con.close();
Done

2022-09-15 20:52 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/util/DataSourceUtil.java
> +        this.password = StaticVariable.PASSWORD;
Done

2022-09-15 20:52 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/view/MainMenu.java
> +                    System.exit(0);
Done

2022-09-15 20:54 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/view/MainMenu.java
> +        Scanner scStr = new Scanner(System.in);
Scanners were closed. Programme doesn't work correctly in switch with only 1 scanner.

2022-09-15 20:54 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/bean/Book.java
> +    private Author a;
Done

2022-09-15 20:55 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/util/DataSourceUtil.java
> +            Class.forName(driverPath);
Done

2022-09-15 20:55 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/dao/impl/SQLBookDAO.java
> +                con.close();
Done

2022-09-15 20:59 UTC, iryna-pantsialeyeva commented on src/finalproject/part1/service/ServiceFactory.java
> +    public static ServiceFactory getInstance() {
As we discussed I'm able not change the method and variable but I remember we should use fabrika only if appropriate.

2022-09-16 11:21 UTC, DimaLamaka approved these changes

2022-09-16 18:34 UTC, merged